/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package monitoringrouter.view;

import java.awt.Font;
import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import javax.swing.DefaultListModel;

/**
 *
 * @author azwarazuhri
 */
public class Ping extends javax.swing.JFrame {

    /**
     * Creates new form Ping
     */
    public Ping() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        pingArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Ping");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        pingArea.setColumns(20);
        pingArea.setRows(5);
        jScrollPane1.setViewportView(pingArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
//         TODO add your handling code here:
        String command;
        try {
	Process p = Runtime.getRuntime().exec("ping "+jTextField1.getText().toString());
	BufferedReader inputStream = new BufferedReader(
            new InputStreamReader(p.getInputStream()));
        //String s = "";
        String s = inputStream.readLine();
        String[] data = new String[10];
        StringBuilder sb = new StringBuilder();
        for(int i=1;i<10;i++){
//            s = inputStream.readLine();
            data[i]=s;
            sb.append(data[i]).append("\n");
            System.out.println(data[i]);
        }
             pingArea.setText(sb.toString());
        }catch(Exception e){
            System.out.println(e);
        }
	// reading output stream of the command
//        while ((s = inputStream.readLine()) != null) {
//        	System.out.println(s);
//                //sb.append(s);
//               // System.out.println(sb.append(s));
//               pingArea.setText(pingArea.getText()+s);
//   
//	}
//         // pingArea.append(s);
//	} catch (Exception e) {
//            e.printStackTrace();
//            }
//    int min = 0;
//    int max = 10;
//    StringBuilder sb = new StringBuilder(128);
//    //sb.append("<html>");
//    for (int n = min; n <= max; n++) {
//        System.out.println(Integer.toString(n));
//        sb.append(n).append("\n");
//    }
    //sb.append("</html>");
    //pingArea.setText(sb.toString());
    
    
//        int a=1;
//        int b=10;
//        StringBuilder tes = new StringBuilder();
//        while(a>10){
//            tes.append(a).append("\n");
//            System.out.println("ini"+tes);
//        }
//        pingArea.setText(""+tes.toString());
    }//GEN-LAST:event_jButton1ActionPerformed
   
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ping.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ping.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ping.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ping.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ping().setVisible(true);
            }
        });
    }

    
    
    
    
    public  void runSystemCommand(String command) {
    try {
	Process p = Runtime.getRuntime().exec(command);
	BufferedReader inputStream = new BufferedReader(
					new InputStreamReader(p.getInputStream()));

	String s = "";
	// reading output stream of the command
        while ((s = inputStream.readLine()) != null) {
		System.out.println(s);
               // pingArea.setText(""+s);
	}

	} catch (Exception e) {
            e.printStackTrace();
            }
	}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextArea pingArea;
    // End of variables declaration//GEN-END:variables
}
